apiVersion: v1
kind: Secret
metadata:
  name: cx-secrets
  namespace: default
type: Opaque
stringData:
  CX_CLIENT_ID: "cx-dhruv-client-id"
  CX_CLIENT_SECRET: "56FqEFUHcSYiVpphj3jUeXpNofqhCBFG"
  CX_TENANT: "sudha"
  CX_BASE_URI: "https://ind.ast.checkmarx.net"
